import type {
  ComparisonColumn,
  ComparisonRow,
} from "@/components/mdx/comparison-table";

export interface ComparisonData {
  columns: ComparisonColumn[];
  rows: ComparisonRow[];
  caption?: string;
  featureLabel?: string;
}

export const COMPARISONS: Record<string, ComparisonData> = {
  "steps-vs-apple-fitness": {
    columns: [
      { key: "steps", label: "Steps", highlight: true },
      { key: "af", label: "Apple Fitness" },
    ],
    rows: [
      { label: "Step Counting", cells: { steps: "✓", af: "✓" } },
      { label: "iPhone Widgets", cells: { steps: "8 widget types", af: "1 basic widget" } },
      { label: "Apple Watch App", cells: { steps: "Native", af: "Native" } },
      { label: "Watch Complications", cells: { steps: "Multiple styles", af: "Activity rings only" } },
      { label: "GPX Export", cells: { steps: "✓", af: "✗" } },
      { label: "Workout Types", cells: { steps: "23+", af: "10+" } },
      { label: "Streak Tracking", cells: { steps: "Daily streaks", af: "Move rings" } },
      { label: "Yearly Insights", cells: { steps: "Wrapped-style", af: "Monthly summaries" } },
      { label: "Personal Records", cells: { steps: "8 PR categories", af: "✗" } },
      { label: "Charts", cells: { steps: "Hourly / weekly / monthly", af: "Weekly summaries" } },
      { label: "Price", cells: { steps: "Free (Pro available)", af: "Free (Fitness+ paid)" } },
    ],
  },
  "steps-vs-strava": {
    columns: [
      { key: "steps", label: "Steps", highlight: true },
      { key: "strava", label: "Strava" },
    ],
    rows: [
      { label: "Step Counting", cells: { steps: "Dedicated", strava: "Not a focus" } },
      { label: "iPhone Widgets", cells: { steps: "8 widget types", strava: "1 basic widget" } },
      { label: "Apple Watch App", cells: { steps: "Native", strava: "Native" } },
      { label: "Watch Complications", cells: { steps: "Multiple styles", strava: "Basic" } },
      { label: "GPX Export", cells: { steps: "Free", strava: "Subscription required" } },
      { label: "Workout Types", cells: { steps: "23+", strava: "30+" } },
      { label: "Streak Tracking", cells: { steps: "✓", strava: "✗" } },
      { label: "Yearly Insights", cells: { steps: "Wrapped-style", strava: "Year in Sport (paid)" } },
      { label: "Personal Records", cells: { steps: "8 PR categories", strava: "Segment-based" } },
      { label: "Social Features", cells: { steps: "✗", strava: "Feed, clubs, kudos" } },
      { label: "Route Planning", cells: { steps: "✗", strava: "Subscription" } },
      { label: "Segments / Leaderboards", cells: { steps: "✗", strava: "✓" } },
      { label: "Charts", cells: { steps: "Hourly / weekly / monthly", strava: "Weekly summaries" } },
      { label: "Price", cells: { steps: "Free (Pro available)", strava: "Free (Summit $11.99/mo)" } },
    ],
  },
  "steps-vs-pedometer-plus-plus": {
    columns: [
      { key: "steps", label: "Steps", highlight: true },
      { key: "p2", label: "Pedometer++" },
    ],
    rows: [
      { label: "Step Counting", cells: { steps: "✓", p2: "✓" } },
      { label: "iPhone Widgets", cells: { steps: "8 widget types", p2: "3 widget types" } },
      { label: "Apple Watch App", cells: { steps: "Native", p2: "Native" } },
      { label: "Watch Complications", cells: { steps: "Multiple styles", p2: "Basic" } },
      { label: "GPX Export", cells: { steps: "✓", p2: "✗" } },
      { label: "Workout Types", cells: { steps: "23+", p2: "Walking only" } },
      { label: "Streak Tracking", cells: { steps: "✓", p2: "✗" } },
      { label: "Yearly Insights", cells: { steps: "Wrapped-style", p2: "✗" } },
      { label: "Personal Records", cells: { steps: "8 PR categories", p2: "✗" } },
      { label: "Charts", cells: { steps: "Hourly / weekly / monthly", p2: "Daily / weekly" } },
      { label: "HealthKit Sync", cells: { steps: "✓", p2: "✓" } },
      { label: "Price", cells: { steps: "Free (Pro available)", p2: "Free (Premium paid)" } },
    ],
  },
  "steps-vs-nike-run-club": {
    columns: [
      { key: "steps", label: "Steps", highlight: true },
      { key: "nrc", label: "Nike Run Club" },
    ],
    rows: [
      { label: "Step Counting", cells: { steps: "Dedicated", nrc: "Basic (via Apple Health)" } },
      { label: "iPhone Widgets", cells: { steps: "8 widget types", nrc: "1 widget" } },
      { label: "Apple Watch App", cells: { steps: "Native", nrc: "Native" } },
      { label: "Watch Complications", cells: { steps: "Multiple styles", nrc: "Run-focused" } },
      { label: "GPX Export", cells: { steps: "✓", nrc: "✗" } },
      { label: "Workout Types", cells: { steps: "23+", nrc: "Running-focused" } },
      { label: "Streak Tracking", cells: { steps: "Daily steps", nrc: "Run streaks" } },
      { label: "Yearly Insights", cells: { steps: "Wrapped-style", nrc: "Monthly recap" } },
      { label: "Personal Records", cells: { steps: "8 PR categories", nrc: "Running PRs only" } },
      { label: "Guided Workouts", cells: { steps: "✗", nrc: "Audio-guided runs" } },
      { label: "Social Features", cells: { steps: "✗", nrc: "Challenges & clubs" } },
      { label: "Charts", cells: { steps: "Hourly / weekly / monthly", nrc: "Run history" } },
      { label: "Price", cells: { steps: "Free (Pro available)", nrc: "Free" } },
    ],
  },
  "best-step-counter-iphone": {
    columns: [
      { key: "steps", label: "Steps", highlight: true },
      { key: "p2", label: "Pedometer++" },
      { key: "sa", label: "StepsApp" },
      { key: "pacer", label: "Pacer" },
    ],
    rows: [
      { label: "Widgets", cells: { steps: "8 types", p2: "3 types", sa: "2 types", pacer: "2 types" } },
      { label: "Watch App", cells: { steps: "Native", p2: "Native", sa: "✓", pacer: "✓" } },
      { label: "Workout Types", cells: { steps: "23+", p2: "Walking only", sa: "3", pacer: "5" } },
      { label: "GPX Export", cells: { steps: "✓", p2: "✗", sa: "✗", pacer: "✗" } },
      { label: "Streaks", cells: { steps: "✓", p2: "✗", sa: "✗", pacer: "✓" } },
      { label: "Yearly Recap", cells: { steps: "✓", p2: "✗", sa: "✗", pacer: "✗" } },
      { label: "Personal Records", cells: { steps: "8", p2: "✗", sa: "✗", pacer: "✗" } },
      { label: "Free Tier", cells: { steps: "✓", p2: "✓", sa: "✓", pacer: "✓" } },
    ],
  },
  "best-step-counter-apple-watch": {
    featureLabel: "Capability",
    columns: [
      { key: "steps", label: "Steps: Workout & Pedometer", highlight: true },
    ],
    rows: [
      { label: "Native Watch App", cells: { steps: "✓" } },
      { label: "Complications", cells: { steps: "Multiple styles" } },
      { label: "iPhone Widgets", cells: { steps: "8 widget types" } },
      { label: "GPX Export", cells: { steps: "✓" } },
      { label: "Yearly Insights", cells: { steps: "✓" } },
      { label: "Streak Tracking", cells: { steps: "✓" } },
      { label: "23+ Workout Types", cells: { steps: "✓" } },
    ],
  },
  "best-pedometer-app-iphone": {
    columns: [
      { key: "steps", label: "Steps", highlight: true },
      { key: "p2", label: "Pedometer++" },
      { key: "sa", label: "StepsApp" },
      { key: "ah", label: "Apple Health" },
    ],
    rows: [
      { label: "Step Counting", cells: { steps: "✓", p2: "✓", sa: "✓", ah: "✓" } },
      { label: "Widgets", cells: { steps: "8 types", p2: "3 types", sa: "2 types", ah: "✗" } },
      { label: "Watch Complications", cells: { steps: "Multiple", p2: "Basic", sa: "✓", ah: "Activity" } },
      { label: "Workout Tracking", cells: { steps: "23+ types", p2: "✗", sa: "3 types", ah: "✗" } },
      { label: "GPX Export", cells: { steps: "✓", p2: "✗", sa: "✗", ah: "✗" } },
      { label: "Streak Tracking", cells: { steps: "✓", p2: "✗", sa: "✗", ah: "✗" } },
      { label: "Yearly Insights", cells: { steps: "✓", p2: "✗", sa: "✗", ah: "✗" } },
      { label: "Calorie Tracking", cells: { steps: "✓", p2: "✓", sa: "✓", ah: "✓" } },
      { label: "Free", cells: { steps: "✓", p2: "✓", sa: "✓", ah: "✓" } },
    ],
  },
  "pedometer-plus-plus-alternatives": {
    caption: "How the top Pedometer++ alternatives compare on iPhone.",
    columns: [
      { key: "p2", label: "Pedometer++" },
      { key: "steps", label: "Steps", highlight: true },
      { key: "sa", label: "StepsApp" },
      { key: "pacer", label: "Pacer" },
    ],
    rows: [
      { label: "Platforms", cells: { p2: "iOS + Watch", steps: "iOS + Watch", sa: "iOS + Watch", pacer: "iOS + Android + Watch" } },
      { label: "Step Counting", cells: { p2: "✓", steps: "✓", sa: "✓", pacer: "✓" } },
      { label: "Widgets", cells: { p2: "3 types", steps: "8 types", sa: "2 types", pacer: "2 types" } },
      { label: "Multi-Sport Workouts", cells: { p2: "Walk / hike focus", steps: "23+ types", sa: "3 types", pacer: "5 types" } },
      { label: "GPX Export", cells: { p2: "✗", steps: "✓", sa: "✗", pacer: "✗" } },
      { label: "Streak Tracking", cells: { p2: "✗", steps: "✓", sa: "✗", pacer: "✓" } },
      { label: "Yearly Recap", cells: { p2: "✗", steps: "Wrapped-style", sa: "✗", pacer: "✗" } },
      { label: "Personal Records", cells: { p2: "✗", steps: "8 categories", sa: "✗", pacer: "✗" } },
      { label: "Social / Community", cells: { p2: "✗", steps: "✗", sa: "✗", pacer: "✓" } },
      { label: "HealthKit Sync", cells: { p2: "✓", steps: "✓", sa: "✓", pacer: "✓" } },
      { label: "Price", cells: { p2: "Free (Premium paid)", steps: "Free (Pro available)", sa: "Free (Pro paid)", pacer: "Free (Premium paid)" } },
    ],
  },
  "fitbit-alternatives": {
    caption: "How the top Fitbit alternatives compare for iPhone step tracking (no wearable required).",
    columns: [
      { key: "fitbit", label: "Fitbit App" },
      { key: "steps", label: "Steps", highlight: true },
      { key: "p2", label: "Pedometer++" },
      { key: "pacer", label: "Pacer" },
    ],
    rows: [
      { label: "Works Without a Device", cells: { fitbit: "Limited (MobileTrack)", steps: "✓", p2: "✓", pacer: "✓" } },
      { label: "Platforms", cells: { fitbit: "iOS + Android", steps: "iOS + Watch", p2: "iOS + Watch", pacer: "iOS + Android + Watch" } },
      { label: "iPhone Widgets", cells: { fitbit: "1 basic", steps: "8 types", p2: "3 types", pacer: "2 types" } },
      { label: "Multi-Sport Workouts", cells: { fitbit: "With device", steps: "23+ types", p2: "Walk / hike focus", pacer: "5 types" } },
      { label: "GPX Export", cells: { fitbit: "✗", steps: "✓ (free)", p2: "✗", pacer: "✗" } },
      { label: "Streak Tracking", cells: { fitbit: "✓", steps: "✓", p2: "✗", pacer: "✓" } },
      { label: "Yearly Recap", cells: { fitbit: "✗", steps: "Wrapped-style", p2: "✗", pacer: "✗" } },
      { label: "HealthKit Sync", cells: { fitbit: "✗", steps: "✓", p2: "✓", pacer: "✓" } },
      { label: "Price", cells: { fitbit: "Free + Premium $9.99/mo", steps: "Free (Pro available)", p2: "Free (Premium paid)", pacer: "Free (Premium paid)" } },
    ],
  },
  "pacer-alternatives": {
    caption: "How the top Pacer alternatives compare on iPhone.",
    columns: [
      { key: "pacer", label: "Pacer" },
      { key: "steps", label: "Steps", highlight: true },
      { key: "p2", label: "Pedometer++" },
      { key: "sa", label: "StepsApp" },
    ],
    rows: [
      { label: "Platforms", cells: { pacer: "iOS + Android + Watch", steps: "iOS + Watch", p2: "iOS + Watch", sa: "iOS + Android + Watch" } },
      { label: "Step Counting", cells: { pacer: "✓", steps: "✓", p2: "✓", sa: "✓" } },
      { label: "iPhone Widgets", cells: { pacer: "2 types", steps: "8 types", p2: "3 types", sa: "2 types" } },
      { label: "Multi-Sport Workouts", cells: { pacer: "5 types", steps: "23+ types", p2: "Walk / hike focus", sa: "GPS (Pro)" } },
      { label: "GPX Export", cells: { pacer: "✗", steps: "✓ (free)", p2: "✗", sa: "✗" } },
      { label: "Streak Tracking", cells: { pacer: "✓", steps: "✓", p2: "✗", sa: "✓" } },
      { label: "Yearly Recap", cells: { pacer: "✗", steps: "Wrapped-style", p2: "✗", sa: "✗" } },
      { label: "Personal Records", cells: { pacer: "✗", steps: "8 categories", p2: "✗", sa: "Awards" } },
      { label: "Social / Community", cells: { pacer: "✓ (challenges)", steps: "✗", p2: "✗", sa: "✓" } },
      { label: "Ad-Free Free Tier", cells: { pacer: "✗ (Premium)", steps: "✓", p2: "✓", sa: "✗ (Pro)" } },
      { label: "Price", cells: { pacer: "Free (Premium paid)", steps: "Free (Pro available)", p2: "Free (Premium paid)", sa: "Free (ads) + Pro" } },
    ],
  },
  "strava-alternatives": {
    caption: "How the top Strava alternatives compare for step and activity tracking on iPhone.",
    columns: [
      { key: "strava", label: "Strava" },
      { key: "steps", label: "Steps", highlight: true },
      { key: "pacer", label: "Pacer" },
      { key: "nrc", label: "Nike Run Club" },
    ],
    rows: [
      { label: "Step Counting", cells: { strava: "Not a focus", steps: "Dedicated", pacer: "✓", nrc: "Basic" } },
      { label: "iPhone Widgets", cells: { strava: "1 basic", steps: "8 types", pacer: "2 types", nrc: "1 widget" } },
      { label: "Apple Watch App", cells: { strava: "Native", steps: "Native", pacer: "✓", nrc: "Native" } },
      { label: "Workout Types", cells: { strava: "30+", steps: "23+", pacer: "5 types", nrc: "Running-focused" } },
      { label: "GPX Export", cells: { strava: "Activities free / routes paid", steps: "✓ (free)", pacer: "✗", nrc: "✗" } },
      { label: "Streak Tracking", cells: { strava: "✗", steps: "✓", pacer: "✓", nrc: "Run streaks" } },
      { label: "Yearly Recap", cells: { strava: "Year in Sport", steps: "Wrapped-style", pacer: "✗", nrc: "Monthly" } },
      { label: "Social Feed / Clubs", cells: { strava: "✓", steps: "✗", pacer: "✓ (challenges)", nrc: "✓" } },
      { label: "Segments / Leaderboards", cells: { strava: "✓", steps: "✗", pacer: "✗", nrc: "✗" } },
      { label: "Price", cells: { strava: "Free (Sub $11.99/mo)", steps: "Free (Pro available)", pacer: "Free (Premium paid)", nrc: "Free" } },
    ],
  },
  "google-fit-alternatives": {
    caption: "How the top Google Fit alternatives compare for iPhone (Steps and Pedometer++ are iOS-only; Pacer is cross-platform).",
    columns: [
      { key: "gfit", label: "Google Fit" },
      { key: "steps", label: "Steps", highlight: true },
      { key: "pacer", label: "Pacer" },
      { key: "p2", label: "Pedometer++" },
    ],
    rows: [
      { label: "Platforms", cells: { gfit: "Winding down", steps: "iOS + Watch", pacer: "iOS + Android + Watch", p2: "iOS + Watch" } },
      { label: "Step Counting", cells: { gfit: "✓", steps: "✓", pacer: "✓", p2: "✓" } },
      { label: "iPhone Widgets", cells: { gfit: "✗", steps: "8 types", pacer: "2 types", p2: "3 types" } },
      { label: "Apple Watch App", cells: { gfit: "✗", steps: "Native", pacer: "✓", p2: "Native" } },
      { label: "Multi-Sport Workouts", cells: { gfit: "Basic", steps: "23+ types", pacer: "5 types", p2: "Walk / hike focus" } },
      { label: "GPX Export", cells: { gfit: "✗", steps: "✓ (free)", pacer: "✗", p2: "✗" } },
      { label: "Yearly Recap", cells: { gfit: "✗", steps: "Wrapped-style", pacer: "✗", p2: "✗" } },
      { label: "Health Data Sync", cells: { gfit: "Google Health / Health Connect", steps: "Apple HealthKit", pacer: "HealthKit + Google", p2: "Apple HealthKit" } },
      { label: "Actively Supported", cells: { gfit: "Retiring (APIs end 2026)", steps: "✓", pacer: "✓", p2: "✓" } },
      { label: "Price", cells: { gfit: "Free", steps: "Free (Pro available)", pacer: "Free (Premium paid)", p2: "Free (Premium paid)" } },
    ],
  },
  "stepsapp-alternatives": {
    caption: "How the top StepsApp alternatives compare on iPhone.",
    columns: [
      { key: "sa", label: "StepsApp" },
      { key: "steps", label: "Steps", highlight: true },
      { key: "p2", label: "Pedometer++" },
      { key: "pacer", label: "Pacer" },
    ],
    rows: [
      { label: "Platforms", cells: { sa: "iOS + Android + Watch", steps: "iOS + Watch", p2: "iOS + Watch", pacer: "iOS + Android + Watch" } },
      { label: "Step Counting", cells: { sa: "✓", steps: "✓", p2: "✓", pacer: "✓" } },
      { label: "Home / Lock Widgets", cells: { sa: "✓", steps: "8 types", p2: "3 types", pacer: "2 types" } },
      { label: "Multi-Sport Workouts", cells: { sa: "GPS (Pro)", steps: "23+ types", p2: "Walk / hike focus", pacer: "5 types" } },
      { label: "GPX Route Export", cells: { sa: "✗", steps: "✓ (free)", p2: "✗", pacer: "✗" } },
      { label: "Streak Tracking", cells: { sa: "✓", steps: "✓", p2: "✗", pacer: "✓" } },
      { label: "Yearly Recap", cells: { sa: "✗", steps: "Wrapped-style", p2: "✗", pacer: "✗" } },
      { label: "Personal Records", cells: { sa: "Awards", steps: "8 categories", p2: "✗", pacer: "✗" } },
      { label: "Social Challenges", cells: { sa: "✓", steps: "✗", p2: "✗", pacer: "✓" } },
      { label: "HealthKit Sync", cells: { sa: "✓", steps: "✓", p2: "✓", pacer: "✓" } },
      { label: "Free Tier", cells: { sa: "Free (ads) + Pro", steps: "Free (Pro available)", p2: "Free (Premium paid)", pacer: "Free (Premium paid)" } },
    ],
  },
};
