// Canonical list of the free web calculators under /tools.
//
// Single source of truth: the /tools directory page renders `title`,
// `description`, `icon`, and `popular`; the llms.txt generators additionally
// read `inputs` / `outputs` so AI crawlers get the parameter contract of each
// calculator without loading the page.

export interface Tool {
  title: string;
  description: string;
  href: string;
  icon: string;
  popular: boolean;
  /** What the calculator asks for. Used only by the llms.txt full reference. */
  inputs: string;
  /** What the calculator returns. Used only by the llms.txt full reference. */
  outputs: string;
}

export const TOOLS: Tool[] = [
  {
    title: "Step Distance Calculator",
    description: "Convert steps to distance or distance to steps based on your height",
    href: "/tools/step-distance-calculator",
    icon: "📏",
    popular: true,
    inputs: "Height, steps or distance",
    outputs: "Distance in km/miles or step count",
  },
  {
    title: "Steps to Calories Calculator",
    description: "Calculate how many calories you burn from your daily steps",
    href: "/tools/steps-to-calories-calculator",
    icon: "🔥",
    popular: true,
    inputs: "Steps, weight, pace",
    outputs: "Calories burned",
  },
  {
    title: "Walking Calories Calculator",
    description: "Calculate calories burned based on walking distance or time",
    href: "/tools/walking-calories-calculator",
    icon: "🚶",
    popular: true,
    inputs: "Distance or time, pace, weight",
    outputs: "Calories burned, MET multiplier used",
  },
  {
    title: "Treadmill Calorie Calculator",
    description: "Calculate treadmill calories by speed, incline, weight and time",
    href: "/tools/treadmill-calorie-calculator",
    icon: "🏃",
    popular: false,
    inputs: "Weight, speed, incline percentage, duration",
    outputs: "Calories burned, MET value, distance, estimated steps, incline comparison table",
  },
  {
    title: "Steps Per Mile Calculator",
    description: "Find out how many steps are in a mile or kilometer",
    href: "/tools/steps-per-mile-calculator",
    icon: "👟",
    popular: false,
    inputs: "Height, optional pace",
    outputs: "Steps per mile, steps per km",
  },
  {
    title: "Walking Time Calculator",
    description: "Estimate how long it takes to walk any distance",
    href: "/tools/walking-time-calculator",
    icon: "⏱️",
    popular: false,
    inputs: "Distance, pace",
    outputs: "Walking time in minutes",
  },
  {
    title: "Daily Step Goal Calculator",
    description: "Get a personalized daily step goal recommendation",
    href: "/tools/daily-step-goal-calculator",
    icon: "🎯",
    popular: false,
    inputs: "Age, sex, weight, height, activity level, goal",
    outputs: "Suggested daily step count",
  },
  {
    title: "Weight Loss Walking Calculator",
    description: "Calculate walking requirements for your weight loss goals",
    href: "/tools/weight-loss-walking-calculator",
    icon: "⚖️",
    popular: false,
    inputs: "Current weight, goal weight, timeline, pace",
    outputs: "Daily steps needed, total weeks",
  },
  {
    title: "BMI Calculator",
    description: "Calculate your Body Mass Index with health insights",
    href: "/tools/bmi-calculator",
    icon: "📊",
    popular: false,
    inputs: "Height, weight",
    outputs: "BMI value, CDC health category",
  },
  {
    title: "Heart Rate Zones Calculator",
    description: "Find your 5 training zones to optimize fat burn and endurance",
    href: "/tools/heart-rate-zones-calculator",
    icon: "❤️",
    popular: true,
    inputs: "Age, max HR, optional resting HR",
    outputs: "Heart rate range for 5 zones",
  },
  {
    title: "Running Pace Calculator",
    description: "Convert pace, speed, and predict race finish times for any distance",
    href: "/tools/running-pace-calculator",
    icon: "⏱️",
    popular: true,
    inputs: "Pace, or distance and time",
    outputs: "min/km, min/mile, km/h, mph",
  },
  {
    title: "Body Fat Percentage Calculator",
    description: "Calculate body fat % using the accurate U.S. Navy method",
    href: "/tools/body-fat-calculator",
    icon: "📐",
    popular: true,
    inputs: "Neck, waist, hip circumference, height, sex",
    outputs: "Body fat %, ACE category",
  },
  {
    title: "Water Intake Calculator",
    description: "Find out how much water you should drink daily based on weight and activity",
    href: "/tools/water-intake-calculator",
    icon: "💧",
    popular: false,
    inputs: "Weight, activity level, climate",
    outputs: "Daily water intake in L or oz",
  },
  {
    title: "Activity to Steps Converter",
    description: "Convert cycling, swimming, yoga, and more into equivalent steps",
    href: "/tools/activity-to-steps-converter",
    icon: "🚴",
    popular: false,
    inputs: "Activity type, duration, intensity",
    outputs: "Equivalent step count",
  },
  {
    title: "Calorie Deficit Calculator",
    description: "Calculate how many calories to eat per day to reach your goal weight",
    href: "/tools/calorie-deficit-calculator",
    icon: "🥗",
    popular: false,
    inputs: "Current weight, goal weight, TDEE, rate per week",
    outputs: "Daily calorie target, deficit size",
  },
  {
    title: "Resting Heart Rate Calculator",
    description: "Check your cardiovascular fitness level and Karvonen heart rate zones",
    href: "/tools/resting-heart-rate-calculator",
    icon: "💓",
    popular: false,
    inputs: "Age, resting heart rate",
    outputs: "Fitness category, Karvonen zones",
  },
  {
    title: "TDEE Calculator",
    description: "Calculate your Total Daily Energy Expenditure and daily calorie needs",
    href: "/tools/tdee-calculator",
    icon: "⚡",
    popular: true,
    inputs: "Age, sex, weight, height, activity level",
    outputs: "BMR, TDEE",
  },
  {
    title: "Macro Calculator",
    description: "Calculate your daily protein, carbs, and fat targets for your fitness goal",
    href: "/tools/macro-calculator",
    icon: "🥩",
    popular: true,
    inputs: "TDEE or body stats, goal",
    outputs: "Grams of protein, carbs, fat",
  },
  {
    title: "Marathon Race Predictor",
    description: "Predict your marathon, half marathon, 10K, and 5K finish times",
    href: "/tools/marathon-pace-predictor",
    icon: "🏅",
    popular: false,
    inputs: "Known race distance and time",
    outputs: "Predicted times for other distances (Riegel formula)",
  },
  {
    title: "VO2 Max Calculator",
    description: "Estimate your aerobic fitness level using heart rate or Cooper test",
    href: "/tools/vo2-max-calculator",
    icon: "🫁",
    popular: false,
    inputs: "Age, max HR or Cooper test distance",
    outputs: "VO2 max estimate, fitness percentile",
  },
  {
    title: "Training Pace Zones",
    description: "Get your 5 personalized running training pace zones from any race result",
    href: "/tools/training-pace-zones",
    icon: "🎯",
    popular: false,
    inputs: "Race distance, race time",
    outputs: "Five pace zones (recovery to interval)",
  },
  {
    title: "Pace to Speed Converter",
    description: "Convert min/km, min/mile, km/h, and mph instantly",
    href: "/tools/pace-to-speed-converter",
    icon: "↔️",
    popular: false,
    inputs: "Pace or speed",
    outputs: "Pace and speed in all units",
  },
  {
    title: "Race Time Predictor",
    description: "Calculate finish time from pace or find the pace needed for your goal time",
    href: "/tools/race-time-predictor",
    icon: "⏱️",
    popular: false,
    inputs: "Distance, pace or target time",
    outputs: "Predicted finish or required pace",
  },
  {
    title: "Distance Equivalent Calculator",
    description: "Convert km, miles, meters, yards — with steps, time, and calories",
    href: "/tools/distance-equivalent-calculator",
    icon: "📏",
    popular: false,
    inputs: "Distance in any unit",
    outputs: "Equivalent units, time, steps, calories",
  },
  {
    title: "GPX Viewer",
    description: "Upload and view GPX files on an interactive map with stats",
    href: "/tools/gpx-viewer",
    icon: "🗺️",
    popular: false,
    inputs: "GPX file",
    outputs: "Map, distance, duration, pace, elevation",
  },
  {
    title: "Strava Stats Generator",
    description: "Turn a run into a transparent stats overlay for Instagram Stories",
    href: "/tools/strava-stats-generator",
    icon: "🏃",
    popular: true,
    inputs: "Run distance, time, pace, or a GPX file",
    outputs: "Transparent PNG stats overlay",
  },
  {
    title: "BMR Calculator",
    description: "Calculate your basal metabolic rate with three clinical formulas",
    href: "/tools/bmr-calculator",
    icon: "🔬",
    popular: true,
    inputs: "Gender, age, weight, height, optional body fat percentage",
    outputs: "BMR from Mifflin-St Jeor, Harris-Benedict and Katch-McArdle, plus daily calories at five activity levels",
  },
  {
    title: "Weight Loss Calculator",
    description: "Daily calorie target and timeline to reach your goal weight",
    href: "/tools/weight-loss-calculator",
    icon: "⚖️",
    popular: true,
    inputs: "Gender, age, height, current weight, goal weight, activity level, rate of loss",
    outputs: "Daily calorie target, deficit, weeks to goal, week-by-week milestones, safety warnings",
  },
  {
    title: "Calories Burned Calculator",
    description: "Calories burned across 50+ activities using MET values",
    href: "/tools/calories-burned-calculator",
    icon: "🔥",
    popular: true,
    inputs: "Activity, body weight, duration",
    outputs: "Gross and net calories, calories per hour, walking and step equivalent, activity comparison table",
  },
  {
    title: "Ideal Weight Calculator",
    description: "Four clinical formulas plus the healthy BMI range for your height",
    href: "/tools/ideal-weight-calculator",
    icon: "🎯",
    popular: false,
    inputs: "Gender, height, optional current weight",
    outputs: "Devine, Robinson, Miller and Hamwi estimates, formula average, healthy BMI weight range",
  },
  {
    title: "Waist to Hip Ratio Calculator",
    description: "Check your waist-to-hip ratio against WHO risk thresholds",
    href: "/tools/waist-to-hip-ratio-calculator",
    icon: "📐",
    popular: false,
    inputs: "Gender, waist circumference, hip circumference",
    outputs: "Waist-to-hip ratio, WHO risk band, waist circumference verdict, target waist for low risk",
  },
];
